language: node_js
node_js:
- 0.10
notifications:
  email:
  - damon.oehlman@nicta.com.au
  irc: irc.freenode.org#rtc.io

env:
  matrix:
    - BROWSER=chrome  BVER=stable
    - BROWSER=chrome  BVER=beta
    - BROWSER=chrome  BVER=unstable
    - BROWSER=firefox BVER=stable
    - BROWSER=firefox BVER=beta
    - BROWSER=firefox BVER=nightly

matrix:
  fast_finish: true

  allow_failures:
    - env: BROWSER=chrome  BVER=unstable
    - env: BROWSER=firefox BVER=nightly

before_install:
  - mkdir -p .testrunner
  # this very next line is what you SHOULD DO!!!
  # - curl -s https://codeload.github.com/DamonOehlman/travis-multirunner/tar.gz/v1.0.0 | tar -xz --strip-components=1 --directory .testrunner
  # but for the purposes of offline friendly this command can run inst
  - ./.testrunner/setup.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true
